name: Build and Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set image tag from commit SHA
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and tag new image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest -t ${{ secrets.DOCKER_USERNAME }}/myapp:$GIT_SHA .

      - name: Push image tags
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:$GIT_SHA
